import type { Club } from "./types";

export const clubs: Club[] = [
  {
    id: "investment-group",
    name: "ISU Investment Group",
    mark: "IG",
    slug: "isu-investment-group",
    college: "Ivy College of Business",
    tagline:
      "Learn to research companies, pitch ideas, and think like an investor.",
    summary:
      "A student-run group focused on equity research and portfolio thinking. Members study individual companies, present investment pitches to the group, and debate the reasoning behind each call. It is one of the most direct ways to practice the skills asked about in finance interviews.",
    academicAreas: ["business"],
    openToAllMajors: true,
    majors: ["Finance", "Accounting", "Economics", "Management"],
    categories: ["Finance", "Professional"],
    careerPaths: ["finance", "accounting", "consulting"],
    goalsServed: ["career", "networking", "skills"],
    experienceTypes: ["professional", "academic"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 hours a week",
    meetingFrequency: "Weekly meetings during the semester",
    bestFor:
      "Students targeting investment banking, asset management, or corporate finance.",
    whatYouDo: [
      "Research public companies and build an investment thesis",
      "Present stock pitches and defend them in front of the group",
      "Follow markets and discuss what moved them that week",
      "Prepare for finance interviews with people a year or two ahead of you",
    ],
    whatYouGain: [
      "A pitch you can actually talk about in an interview",
      "Working knowledge of valuation and financial statements",
      "Connections to upperclassmen who have already recruited",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "real-estate-club",
    name: "Real Estate Club",
    mark: "RE",
    slug: "real-estate-club",
    college: "Ivy College of Business",
    tagline:
      "Explore development, brokerage, and real estate investment with people in the industry.",
    summary:
      "Built around the business side of property. Meetings bring in developers, brokers, and lenders, and members work through how real deals get financed and built. A practical way to find out whether real estate is a career you want before you commit to it.",
    academicAreas: ["business", "design"],
    openToAllMajors: true,
    majors: ["Finance", "Marketing", "Construction Engineering", "Architecture"],
    categories: ["Real Estate", "Professional"],
    careerPaths: ["real-estate", "finance", "architecture"],
    goalsServed: ["career", "networking", "skills"],
    experienceTypes: ["professional", "projects"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 hours a week",
    meetingFrequency: "Meetings every other week",
    bestFor:
      "Students curious about development, brokerage, or property investment.",
    whatYouDo: [
      "Hear from developers, brokers, and lenders working in the Midwest",
      "Walk through how a real project gets underwritten and financed",
      "Visit properties and developments when tours are arranged",
      "Meet alumni working across commercial and residential real estate",
    ],
    whatYouGain: [
      "A clear picture of the roles that exist in real estate",
      "Vocabulary and deal intuition you will not get in a lecture",
      "Contacts at regional firms that hire interns",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "fma",
    name: "Financial Management Association",
    mark: "FMA",
    slug: "financial-management-association",
    college: "Ivy College of Business",
    tagline:
      "Career preparation for finance students, built around employers and alumni.",
    summary:
      "The professional home base for finance majors. FMA runs employer sessions, resume and interview preparation, and alumni panels aimed squarely at landing internships. Less about theory, more about getting the offer.",
    academicAreas: ["business"],
    openToAllMajors: false,
    majors: ["Finance", "Accounting", "Economics"],
    categories: ["Finance", "Professional"],
    careerPaths: ["finance", "accounting", "consulting"],
    goalsServed: ["career", "networking", "skills"],
    experienceTypes: ["professional"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Weekly speaker and workshop sessions",
    bestFor: "Finance students who want structured internship preparation.",
    whatYouDo: [
      "Attend employer and alumni sessions throughout the semester",
      "Work through resume reviews and mock interviews",
      "Learn how finance recruiting timelines actually work",
      "Meet recruiters before they come to campus",
    ],
    whatYouGain: [
      "A resume that survives a first-round screen",
      "Interview practice before it counts",
      "Direct exposure to firms that recruit at Iowa State",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "beta-alpha-psi",
    name: "Beta Alpha Psi",
    mark: "BAP",
    slug: "beta-alpha-psi",
    college: "Ivy College of Business",
    tagline:
      "The honor organization for accounting, finance, and information systems students.",
    summary:
      "A professional honor organization with academic requirements for full membership. Programming centers on accounting firms, technical sessions, and service. Candidates typically need a minimum GPA and completed coursework in the major.",
    academicAreas: ["business"],
    openToAllMajors: false,
    majors: ["Accounting", "Finance", "Management Information Systems"],
    categories: ["Accounting", "Honor Society", "Professional"],
    careerPaths: ["accounting", "finance", "consulting"],
    goalsServed: ["career", "networking", "leadership"],
    experienceTypes: ["professional", "academic", "service"],
    commitmentLevel: "involved",
    commitmentText: "About 4 to 6 hours a week",
    meetingFrequency: "Weekly professional meetings plus service hours",
    bestFor:
      "Accounting and MIS students recruiting for public accounting or advisory.",
    whatYouDo: [
      "Attend technical and professional sessions led by firms",
      "Complete service and professional hour requirements",
      "Build relationships with recruiters from accounting firms",
      "Take on committee and officer responsibilities",
    ],
    whatYouGain: [
      "A credential recruiters in accounting recognize",
      "Consistent face time with firms that hire at Iowa State",
      "Leadership experience with real accountability",
    ],
    beginnerFriendly: false,
    freshmenWelcome: false,
    applicationRequired: true,
  },
  {
    id: "ama",
    name: "American Marketing Association",
    mark: "AMA",
    slug: "american-marketing-association",
    college: "Ivy College of Business",
    tagline:
      "Practice marketing on real briefs instead of only reading about it.",
    summary:
      "The Iowa State chapter of AMA connects marketing students with agencies, brand teams, and competitions. Members work on campaigns, hear from practitioners, and build portfolio pieces they can show employers.",
    academicAreas: ["business", "liberal-arts"],
    openToAllMajors: true,
    majors: ["Marketing", "Advertising", "Journalism", "Graphic Design"],
    categories: ["Marketing", "Professional"],
    careerPaths: ["marketing", "media-comm", "entrepreneurship"],
    goalsServed: ["career", "networking", "skills", "hands-on"],
    experienceTypes: ["professional", "competition", "projects"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Weekly meetings with project work between",
    bestFor:
      "Students who want agency, brand, or digital marketing experience.",
    whatYouDo: [
      "Work on campaign projects and marketing competitions",
      "Hear from agency and brand-side marketers",
      "Build portfolio work you can show in interviews",
      "Attend regional and national AMA events",
    ],
    whatYouGain: [
      "Portfolio pieces instead of a blank resume line",
      "Feedback from people who market for a living",
      "A network across agencies and in-house teams",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "ascm",
    name: "Association for Supply Chain Management",
    mark: "SCM",
    slug: "association-for-supply-chain-management",
    college: "Ivy College of Business",
    tagline:
      "See how products actually move, from plant tours to logistics case work.",
    summary:
      "The supply chain student organization at Iowa State. Programming leans heavily on employer engagement and site visits, which is unusually valuable in a field where most students have never seen a distribution center.",
    academicAreas: ["business", "engineering"],
    openToAllMajors: true,
    majors: ["Supply Chain Management", "Industrial Engineering", "Management"],
    categories: ["Supply Chain", "Professional"],
    careerPaths: ["supply-chain", "consulting", "engineering-design"],
    goalsServed: ["career", "networking", "skills"],
    experienceTypes: ["professional", "competition"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 hours a week",
    meetingFrequency: "Weekly meetings plus periodic site visits",
    bestFor:
      "Supply chain and industrial engineering students headed into operations.",
    whatYouDo: [
      "Tour manufacturing plants and distribution facilities",
      "Compete in supply chain case competitions",
      "Meet recruiters from logistics and manufacturing companies",
      "Learn certification paths available through ASCM",
    ],
    whatYouGain: [
      "Real exposure to operations before your first internship",
      "Case competition experience that interviews well",
      "A pipeline to employers that hire heavily in the Midwest",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "mis-club",
    name: "Management Information Systems Club",
    mark: "MIS",
    slug: "mis-club",
    college: "Ivy College of Business",
    tagline: "Where business and technology careers overlap.",
    summary:
      "For students working at the intersection of business process and technology. Meetings cover analytics tools, IT consulting paths, and the employers who hire MIS majors, with a steady stream of company visits.",
    academicAreas: ["business", "computing"],
    openToAllMajors: true,
    majors: [
      "Management Information Systems",
      "Computer Science",
      "Business Analytics",
    ],
    categories: ["Technology", "Professional"],
    careerPaths: ["data-ai", "consulting", "software", "cybersecurity"],
    goalsServed: ["career", "networking", "skills"],
    experienceTypes: ["professional", "academic"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Weekly meetings with employer guests",
    bestFor: "MIS and analytics students exploring technology consulting.",
    whatYouDo: [
      "Meet companies hiring for analyst and IT consulting roles",
      "Work through tools like SQL, Tableau, and Power BI",
      "Hear how alumni moved from MIS coursework into tech careers",
      "Get help tailoring a resume for technical business roles",
    ],
    whatYouGain: [
      "Clarity on which technology career actually fits you",
      "Practical tool experience employers ask about",
      "A network inside consulting and corporate IT",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "shrm",
    name: "Society for Human Resource Management",
    mark: "HR",
    slug: "society-for-human-resource-management",
    college: "Ivy College of Business",
    tagline: "The people side of business, taught by people who do it.",
    summary:
      "Iowa State's SHRM chapter focuses on human resource careers: recruiting, compensation, employee relations, and organizational development. Sessions are led by HR professionals and cover both the work and the certification path.",
    academicAreas: ["business", "human-sciences"],
    openToAllMajors: true,
    majors: ["Management", "Psychology", "Communication Studies"],
    categories: ["Human Resources", "Professional"],
    careerPaths: ["consulting", "media-comm"],
    goalsServed: ["career", "networking", "skills", "community"],
    experienceTypes: ["professional", "community"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Meetings every other week",
    bestFor: "Students drawn to recruiting, HR, or organizational roles.",
    whatYouDo: [
      "Hear from HR professionals across different industries",
      "Prepare for HR certification exams offered to students",
      "Practice interviewing from both sides of the table",
      "Connect with companies recruiting for HR internships",
    ],
    whatYouGain: [
      "A realistic view of what HR work involves day to day",
      "A head start on professional certification",
      "Interview skills that transfer to any field",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "180-degrees-consulting",
    name: "180 Degrees Consulting",
    mark: "180",
    slug: "180-degrees-consulting",
    college: "Ivy College of Business",
    tagline:
      "Do real consulting work for nonprofits and social enterprises.",
    summary:
      "The Iowa State branch of an international student consultancy. Teams take on scoped engagements for nonprofit clients and deliver actual recommendations. Membership is selective and the work is closer to a real project than a class exercise.",
    academicAreas: ["business", "liberal-arts", "engineering"],
    openToAllMajors: true,
    majors: ["Management", "Finance", "Marketing", "Economics"],
    categories: ["Consulting", "Professional", "Service"],
    careerPaths: ["consulting", "finance", "marketing", "entrepreneurship"],
    goalsServed: ["career", "skills", "hands-on", "leadership"],
    experienceTypes: ["professional", "projects", "service"],
    commitmentLevel: "involved",
    commitmentText: "About 5 hours a week during an engagement",
    meetingFrequency: "Weekly team meetings plus client work",
    bestFor:
      "Students recruiting for consulting who want a client project on their resume.",
    whatYouDo: [
      "Join a small team assigned to a nonprofit client",
      "Run research, analysis, and stakeholder interviews",
      "Build and deliver a final recommendation deck",
      "Get coached by members who have interned in consulting",
    ],
    whatYouGain: [
      "A genuine client engagement to talk through in interviews",
      "Structured problem solving and deck-building practice",
      "Teamwork under a real deadline with a real client",
    ],
    beginnerFriendly: false,
    freshmenWelcome: true,
    applicationRequired: true,
  },
  {
    id: "women-in-business",
    name: "Women in Business",
    mark: "WIB",
    slug: "women-in-business",
    college: "Ivy College of Business",
    tagline:
      "Professional development and mentorship for women building business careers.",
    summary:
      "Combines career programming with mentorship and community. Members connect with alumnae and employers while building a peer group that lasts past graduation. Open to all students regardless of major.",
    academicAreas: ["business"],
    openToAllMajors: true,
    majors: ["Finance", "Marketing", "Accounting", "Management"],
    categories: ["Professional", "Community"],
    careerPaths: ["finance", "marketing", "consulting", "accounting"],
    goalsServed: ["career", "networking", "community", "leadership"],
    experienceTypes: ["professional", "community"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Meetings every other week",
    bestFor:
      "Students who want career programming and a peer group at the same time.",
    whatYouDo: [
      "Attend professional development and alumnae panels",
      "Join a mentorship pairing with an upperclassman or professional",
      "Work on resume, negotiation, and interview skills",
      "Take part in social events across the semester",
    ],
    whatYouGain: [
      "A mentor who has already done what you are trying to do",
      "A professional network that keeps going after graduation",
      "Confidence in rooms where you are the newest person",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "entrepreneur-club",
    name: "Entrepreneur Club",
    mark: "EC",
    slug: "entrepreneur-club",
    college: "Ivy College of Business",
    tagline: "For students who want to build something, not just study it.",
    summary:
      "A community for student founders and the founder-curious. Meetings mix guest founders, pitch practice, and working sessions on members' own ideas. Connects into Iowa State's broader entrepreneurship resources.",
    academicAreas: ["business", "engineering", "computing", "design"],
    openToAllMajors: true,
    majors: ["Entrepreneurship", "Management", "Computer Science", "Marketing"],
    categories: ["Entrepreneurship", "Community"],
    careerPaths: ["entrepreneurship", "marketing", "consulting", "finance"],
    goalsServed: [
      "entrepreneurship",
      "community",
      "skills",
      "hands-on",
      "networking",
    ],
    experienceTypes: ["community", "projects", "professional"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Weekly meetings",
    bestFor: "Students with an idea, or who want to be around people who have one.",
    whatYouDo: [
      "Hear from founders about what actually happened, not the highlight reel",
      "Pitch your idea and get blunt feedback",
      "Find cofounders among people in other majors",
      "Learn what campus funding and competitions are available",
    ],
    whatYouGain: [
      "Momentum on an idea you have been sitting on",
      "A group that takes your side project seriously",
      "Pitch practice before the stakes are real",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "cyclone-racing",
    name: "Cyclone Racing",
    mark: "CR",
    slug: "cyclone-racing",
    college: "College of Engineering",
    tagline:
      "Design, build, and race a vehicle against university teams nationwide.",
    summary:
      "Iowa State's Formula SAE and Baja SAE teams. Students design and manufacture competition vehicles from scratch, then race them. It is one of the largest time commitments on campus and one of the most respected lines on an engineering resume.",
    academicAreas: ["engineering", "computing"],
    openToAllMajors: false,
    majors: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Materials Engineering",
      "Aerospace Engineering",
    ],
    categories: ["Engineering", "Competition", "Project Team"],
    careerPaths: ["engineering-design", "software"],
    goalsServed: ["hands-on", "skills", "career", "leadership", "community"],
    experienceTypes: ["projects", "competition"],
    commitmentLevel: "high",
    commitmentText: "10 or more hours a week, heavier near competition",
    meetingFrequency: "Ongoing shop hours plus team meetings",
    bestFor:
      "Engineering students who want manufacturing and design experience now.",
    whatYouDo: [
      "Design subsystems in CAD and take them through analysis",
      "Machine, weld, and assemble parts in the shop",
      "Test the vehicle and iterate on what breaks",
      "Travel to compete against other university teams",
    ],
    whatYouGain: [
      "Hands-on manufacturing skill most graduates do not have",
      "A design project you can walk an interviewer through in detail",
      "Recruiters who specifically look for this team",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "swe",
    name: "Society of Women Engineers",
    mark: "SWE",
    slug: "society-of-women-engineers",
    college: "College of Engineering",
    tagline:
      "Career support, mentorship, and community for engineering students.",
    summary:
      "One of the larger and better-resourced engineering organizations on campus. SWE runs corporate networking, outreach to K-12 students, and a mentorship structure, and sends members to a large national conference with its own career fair.",
    academicAreas: ["engineering", "computing"],
    openToAllMajors: true,
    majors: [
      "Mechanical Engineering",
      "Industrial Engineering",
      "Computer Engineering",
      "Chemical Engineering",
    ],
    categories: ["Engineering", "Professional", "Community"],
    careerPaths: ["engineering-design", "software", "data-ai"],
    goalsServed: ["career", "networking", "community", "leadership", "skills"],
    experienceTypes: ["professional", "community", "service"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Regular general meetings plus events",
    bestFor:
      "Engineering students who want both recruiting access and a community.",
    whatYouDo: [
      "Meet corporate sponsors that recruit engineering interns",
      "Join mentorship pairings with students and professionals",
      "Run outreach events introducing engineering to younger students",
      "Attend the national conference and its career fair",
    ],
    whatYouGain: [
      "Employer access outside the normal career fair scramble",
      "A mentor inside your major",
      "Leadership roles that scale with how much you put in",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "nsbe",
    name: "National Society of Black Engineers",
    mark: "NSBE",
    slug: "national-society-of-black-engineers",
    college: "College of Engineering",
    tagline:
      "Academic support, professional development, and community for Black engineering students.",
    summary:
      "NSBE combines study support, corporate recruiting, and outreach. The national convention gives members access to a large engineering career fair, and the campus chapter provides a consistent academic and social base.",
    academicAreas: ["engineering", "computing"],
    openToAllMajors: true,
    majors: [
      "Mechanical Engineering",
      "Computer Engineering",
      "Civil Engineering",
      "Software Engineering",
    ],
    categories: ["Engineering", "Professional", "Community"],
    careerPaths: ["engineering-design", "software", "data-ai"],
    goalsServed: ["career", "networking", "community", "leadership"],
    experienceTypes: ["professional", "community", "service"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Regular chapter meetings plus events",
    bestFor:
      "Engineering students looking for both a support network and recruiting access.",
    whatYouDo: [
      "Attend chapter meetings and study sessions",
      "Connect with corporate partners recruiting engineers",
      "Take part in outreach to local students",
      "Travel to regional and national NSBE conventions",
    ],
    whatYouGain: [
      "A career fair many of your classmates never attend",
      "Academic support from people in your courses",
      "Leadership experience within a national organization",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "shpe",
    name: "Society of Hispanic Professional Engineers",
    mark: "SHPE",
    slug: "society-of-hispanic-professional-engineers",
    college: "College of Engineering",
    tagline:
      "Professional development and community for Hispanic students in STEM.",
    summary:
      "SHPE supports members through recruiting, mentorship, and outreach while maintaining a strong social core. The national convention is a significant recruiting opportunity for members who attend.",
    academicAreas: ["engineering", "computing"],
    openToAllMajors: true,
    majors: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Computer Science",
      "Industrial Engineering",
    ],
    categories: ["Engineering", "Professional", "Community"],
    careerPaths: ["engineering-design", "software"],
    goalsServed: ["career", "networking", "community", "leadership"],
    experienceTypes: ["professional", "community", "service"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 hours a week",
    meetingFrequency: "Regular chapter meetings plus events",
    bestFor: "STEM students who want mentorship alongside recruiting access.",
    whatYouDo: [
      "Attend chapter meetings and professional workshops",
      "Meet corporate partners who sponsor the chapter",
      "Mentor and get mentored within the chapter",
      "Attend the national SHPE convention",
    ],
    whatYouGain: [
      "Employer conversations outside the standard career fair",
      "A community that makes a large college feel smaller",
      "Officer experience if you want it",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "asme",
    name: "American Society of Mechanical Engineers",
    mark: "ASME",
    slug: "american-society-of-mechanical-engineers",
    college: "College of Engineering",
    tagline:
      "The professional society for mechanical engineering students.",
    summary:
      "ASME's student section runs industry speakers, plant tours, and design competitions. It is a straightforward way for mechanical engineering students to meet employers and see where the degree actually leads.",
    academicAreas: ["engineering"],
    openToAllMajors: false,
    majors: ["Mechanical Engineering", "Aerospace Engineering", "Materials Engineering"],
    categories: ["Engineering", "Professional"],
    careerPaths: ["engineering-design"],
    goalsServed: ["career", "networking", "skills", "hands-on"],
    experienceTypes: ["professional", "projects", "competition"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Meetings every other week",
    bestFor: "Mechanical engineering students wanting industry exposure early.",
    whatYouDo: [
      "Hear from practicing mechanical engineers about their work",
      "Tour manufacturing and design facilities",
      "Enter ASME design competitions",
      "Meet recruiters at chapter-sponsored events",
    ],
    whatYouGain: [
      "A sense of which mechanical engineering path fits you",
      "Company contacts before career fair week",
      "Optional competition experience without a full project team",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "ieee",
    name: "IEEE Student Branch",
    mark: "IEEE",
    slug: "ieee-student-branch",
    college: "College of Engineering",
    tagline:
      "Electrical, computer, and software engineering, from workshops to competitions.",
    summary:
      "The campus branch of the world's largest technical professional organization. Programming ranges from hands-on hardware workshops to industry talks, with access to IEEE technical resources and competitions.",
    academicAreas: ["engineering", "computing"],
    openToAllMajors: false,
    majors: [
      "Electrical Engineering",
      "Computer Engineering",
      "Software Engineering",
      "Computer Science",
    ],
    categories: ["Engineering", "Technology", "Professional"],
    careerPaths: ["engineering-design", "software", "cybersecurity"],
    goalsServed: ["skills", "hands-on", "career", "networking"],
    experienceTypes: ["projects", "academic", "professional", "competition"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Regular meetings plus workshop sessions",
    bestFor:
      "Electrical and computer engineering students who like building hardware.",
    whatYouDo: [
      "Build and debug circuits in hands-on workshops",
      "Work on embedded and robotics side projects",
      "Attend technical talks from industry engineers",
      "Enter IEEE student competitions",
    ],
    whatYouGain: [
      "Lab skills beyond what coursework covers",
      "Project work you can demo",
      "Access to IEEE technical resources and its network",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "aiche",
    name: "American Institute of Chemical Engineers",
    mark: "AIChE",
    slug: "american-institute-of-chemical-engineers",
    college: "College of Engineering",
    tagline:
      "Industry connections and technical community for chemical engineering students.",
    summary:
      "The AIChE student chapter connects chemical engineering students with process industries through speakers, plant tours, and competitions such as Chem-E-Car. It also functions as an academic support network within a demanding major.",
    academicAreas: ["engineering"],
    openToAllMajors: false,
    majors: ["Chemical Engineering", "Biological Systems Engineering"],
    categories: ["Engineering", "Professional", "Competition"],
    careerPaths: ["engineering-design", "healthcare"],
    goalsServed: ["career", "networking", "hands-on", "skills"],
    experienceTypes: ["professional", "projects", "competition", "academic"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 4 hours a week",
    meetingFrequency: "Regular meetings plus project team time",
    bestFor:
      "Chemical engineering students headed into process or manufacturing roles.",
    whatYouDo: [
      "Tour chemical and process plants",
      "Join competition teams such as Chem-E-Car",
      "Hear from engineers working in process industries",
      "Study together through the harder core courses",
    ],
    whatYouGain: [
      "Employer exposure specific to chemical engineering",
      "A hands-on competition project if you want one",
      "An academic support group inside a tough curriculum",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "asce",
    name: "American Society of Civil Engineers",
    mark: "ASCE",
    slug: "american-society-of-civil-engineers",
    college: "College of Engineering",
    tagline:
      "Concrete canoe, steel bridge, and the civil engineering profession.",
    summary:
      "The civil engineering student chapter, known for competition teams that design and build a concrete canoe and a steel bridge for regional competition. Also runs employer engagement and licensure guidance.",
    academicAreas: ["engineering"],
    openToAllMajors: false,
    majors: ["Civil Engineering", "Construction Engineering", "Environmental Engineering"],
    categories: ["Engineering", "Competition", "Professional"],
    careerPaths: ["engineering-design", "architecture"],
    goalsServed: ["hands-on", "career", "networking", "skills", "community"],
    experienceTypes: ["projects", "competition", "professional"],
    commitmentLevel: "involved",
    commitmentText: "About 4 to 6 hours a week on a competition team",
    meetingFrequency: "Chapter meetings plus build sessions",
    bestFor:
      "Civil and construction students who want to build something physical.",
    whatYouDo: [
      "Design and build a concrete canoe or steel bridge",
      "Compete at the regional student conference",
      "Meet firms hiring civil and construction interns",
      "Learn what professional licensure actually requires",
    ],
    whatYouGain: [
      "A physical project with a real deadline and real testing",
      "Construction and fabrication experience",
      "Direct contact with regional engineering firms",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "engineers-without-borders",
    name: "Engineers Without Borders",
    mark: "EWB",
    slug: "engineers-without-borders",
    college: "College of Engineering",
    tagline:
      "Apply engineering to community infrastructure projects that get built.",
    summary:
      "Student teams partner with communities on infrastructure projects such as water and sanitation systems, taking them from assessment through design and implementation. The projects run across multiple years, so members see work through real constraints.",
    academicAreas: ["engineering", "agriculture"],
    openToAllMajors: true,
    majors: ["Civil Engineering", "Environmental Engineering", "Mechanical Engineering"],
    categories: ["Engineering", "Service", "Project Team"],
    careerPaths: ["engineering-design", "agriculture-food"],
    goalsServed: ["hands-on", "skills", "community", "leadership"],
    experienceTypes: ["projects", "service", "community"],
    commitmentLevel: "involved",
    commitmentText: "About 4 to 5 hours a week",
    meetingFrequency: "Weekly project team meetings",
    bestFor:
      "Engineering students who want their work to have a visible outcome.",
    whatYouDo: [
      "Assess a community need and scope an engineering response",
      "Design systems under real budget and material constraints",
      "Fundraise and plan implementation logistics",
      "Travel with the project team when trips are scheduled",
    ],
    whatYouGain: [
      "Full project lifecycle experience, not just a design phase",
      "Practice explaining engineering to non-engineers",
      "A project with genuine stakes behind it",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "cardinal-space-mining",
    name: "Cardinal Space Mining",
    mark: "CSM",
    slug: "cardinal-space-mining",
    college: "College of Engineering",
    tagline:
      "Build an autonomous mining robot for NASA's university competition.",
    summary:
      "A multidisciplinary project team that designs, builds, and programs a robot to excavate simulated regolith for NASA's student competition. The team spans mechanical, electrical, and software work.",
    academicAreas: ["engineering", "computing"],
    openToAllMajors: false,
    majors: [
      "Mechanical Engineering",
      "Computer Engineering",
      "Software Engineering",
      "Aerospace Engineering",
    ],
    categories: ["Engineering", "Robotics", "Competition"],
    careerPaths: ["engineering-design", "software", "data-ai"],
    goalsServed: ["hands-on", "skills", "career", "leadership"],
    experienceTypes: ["projects", "competition"],
    commitmentLevel: "high",
    commitmentText: "8 or more hours a week, heavier near competition",
    meetingFrequency: "Ongoing build sessions plus team meetings",
    bestFor:
      "Students who want robotics and autonomy experience on a real deadline.",
    whatYouDo: [
      "Design mechanical subsystems for an excavation robot",
      "Write control and autonomy software",
      "Integrate sensors, electronics, and power systems",
      "Compete against other universities in the NASA challenge",
    ],
    whatYouGain: [
      "Robotics and autonomy experience that is hard to get in class",
      "Cross-discipline teamwork with a hard deadline",
      "A project that stands out in technical interviews",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "acm",
    name: "Association for Computing Machinery",
    mark: "ACM",
    slug: "association-for-computing-machinery",
    college: "College of Liberal Arts and Sciences",
    tagline:
      "The computer science community on campus: workshops, talks, and contests.",
    summary:
      "Iowa State's ACM student chapter runs technical workshops, programming contests, and industry talks. It is the default place to find other CS students working on side projects and preparing for technical interviews.",
    academicAreas: ["computing", "engineering"],
    openToAllMajors: true,
    majors: ["Computer Science", "Software Engineering", "Data Science"],
    categories: ["Technology", "Academic", "Community"],
    careerPaths: ["software", "data-ai", "cybersecurity"],
    goalsServed: ["skills", "career", "community", "networking", "hands-on"],
    experienceTypes: ["academic", "projects", "competition", "professional"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 3 hours a week",
    meetingFrequency: "Regular meetings and workshop nights",
    bestFor:
      "Computer science students preparing for technical interviews and projects.",
    whatYouDo: [
      "Attend technical workshops on tools and languages",
      "Practice for programming contests and technical interviews",
      "Hear from software engineers about their teams and stacks",
      "Find people to build side projects with",
    ],
    whatYouGain: [
      "Interview preparation with people in the same position",
      "Exposure to tools outside the required curriculum",
      "A group that keeps your side project from dying",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "iasg",
    name: "Information Assurance Student Group",
    mark: "IASG",
    slug: "information-assurance-student-group",
    college: "College of Engineering",
    tagline:
      "Hands-on cybersecurity, from capture the flag to cyber defense competitions.",
    summary:
      "Iowa State's cybersecurity student group, connected to the university's long-running cyber defense competition infrastructure. Members practice offensive and defensive security in a controlled environment and compete as teams.",
    academicAreas: ["computing", "engineering"],
    openToAllMajors: true,
    majors: ["Cyber Security Engineering", "Computer Science", "Computer Engineering", "Management Information Systems"],
    categories: ["Cybersecurity", "Technology", "Competition"],
    careerPaths: ["cybersecurity", "software", "data-ai"],
    goalsServed: ["skills", "hands-on", "career", "community"],
    experienceTypes: ["projects", "competition", "academic"],
    commitmentLevel: "involved",
    commitmentText: "About 4 hours a week, more before competitions",
    meetingFrequency: "Weekly meetings plus lab time",
    bestFor:
      "Students targeting security roles who want practice, not just theory.",
    whatYouDo: [
      "Practice attacking and defending systems in an isolated lab",
      "Compete in cyber defense competitions and capture the flag events",
      "Learn tooling used in real security work",
      "Meet employers recruiting specifically for security roles",
    ],
    whatYouGain: [
      "Practical security skills employers test for",
      "Competition results worth putting on a resume",
      "Access to one of Iowa State's strongest technical niches",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "data-science-club",
    name: "Data Science Club",
    mark: "DS",
    slug: "data-science-club",
    college: "College of Liberal Arts and Sciences",
    tagline: "Work with real datasets alongside people learning the same tools.",
    summary:
      "A project and workshop oriented group for students working with data. Activities span Python and R tooling, machine learning fundamentals, and competition-style problems, with an emphasis on producing work you can show.",
    academicAreas: ["computing", "business", "liberal-arts"],
    openToAllMajors: true,
    majors: ["Data Science", "Statistics", "Computer Science", "Business Analytics"],
    categories: ["Data", "Technology", "Academic"],
    careerPaths: ["data-ai", "software", "consulting"],
    goalsServed: ["skills", "hands-on", "career", "networking"],
    experienceTypes: ["projects", "academic", "competition"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Weekly workshops and project sessions",
    bestFor:
      "Students who want portfolio projects in analytics or machine learning.",
    whatYouDo: [
      "Work through datasets end to end, from cleaning to a result",
      "Learn Python, R, and modeling tools in workshop format",
      "Enter data competitions as a team",
      "Present findings to the group",
    ],
    whatYouGain: [
      "Portfolio projects that beat a list of coursework",
      "Practice explaining analysis to an audience",
      "A peer group learning the same stack",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "aias",
    name: "American Institute of Architecture Students",
    mark: "AIAS",
    slug: "american-institute-of-architecture-students",
    college: "College of Design",
    tagline:
      "Studio culture, firm connections, and the path to architectural licensure.",
    summary:
      "The student chapter connecting architecture students to the profession. Programming covers firm visits, portfolio review, licensure guidance, and design competitions, alongside the social structure of studio life.",
    academicAreas: ["design"],
    openToAllMajors: false,
    majors: ["Architecture", "Interior Design", "Landscape Architecture"],
    categories: ["Design", "Professional", "Community"],
    careerPaths: ["architecture", "real-estate"],
    goalsServed: ["career", "networking", "community", "skills"],
    experienceTypes: ["professional", "projects", "community", "competition"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Regular chapter meetings plus events",
    bestFor: "Design students who want firm exposure and portfolio feedback.",
    whatYouDo: [
      "Visit architecture firms and see how practices are run",
      "Get portfolio reviews from practicing architects",
      "Enter design competitions",
      "Learn what licensure requires after graduation",
    ],
    whatYouGain: [
      "Portfolio feedback from outside the studio critique loop",
      "Contacts at firms that hire interns from Iowa State",
      "A clearer view of the licensure path",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "agronomy-club",
    name: "Agronomy Club",
    mark: "AG",
    slug: "agronomy-club",
    college: "College of Agriculture and Life Sciences",
    tagline:
      "Crops, soils, and the industry that depends on getting both right.",
    summary:
      "One of the longest-running student organizations in the college. Members compete in crops and soils judging, attend industry events, and connect with agronomy employers across the Midwest.",
    academicAreas: ["agriculture"],
    openToAllMajors: true,
    majors: ["Agronomy", "Agricultural Business", "Environmental Science"],
    categories: ["Agriculture", "Professional", "Competition"],
    careerPaths: ["agriculture-food", "engineering-design"],
    goalsServed: ["career", "networking", "hands-on", "skills", "community"],
    experienceTypes: ["professional", "competition", "academic", "community"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Regular meetings plus judging practice",
    bestFor:
      "Agronomy and ag business students headed into crop production or agribusiness.",
    whatYouDo: [
      "Train for and compete in crops and soils judging contests",
      "Meet employers across seed, chemical, and equipment companies",
      "Attend industry conferences and field events",
      "Take part in long-running club traditions and fundraisers",
    ],
    whatYouGain: [
      "Technical judging skill recognized across the industry",
      "A recruiting network in Midwest agriculture",
      "A tight community within a large college",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "ag-business-club",
    name: "Agricultural Business Club",
    mark: "ABC",
    slug: "agricultural-business-club",
    college: "College of Agriculture and Life Sciences",
    tagline:
      "The business side of agriculture: markets, finance, and agribusiness careers.",
    summary:
      "Focused on careers where agriculture meets business, including grain marketing, ag lending, farm management, and agribusiness sales. Programming is employer-heavy and practical.",
    academicAreas: ["agriculture", "business"],
    openToAllMajors: true,
    majors: ["Agricultural Business", "Agricultural Studies", "Finance", "Economics"],
    categories: ["Agriculture", "Business", "Professional"],
    careerPaths: ["agriculture-food", "finance", "supply-chain", "marketing"],
    goalsServed: ["career", "networking", "skills"],
    experienceTypes: ["professional", "academic"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Meetings every other week",
    bestFor:
      "Students combining agriculture with finance, sales, or management.",
    whatYouDo: [
      "Hear from ag lenders, grain merchandisers, and agribusiness leaders",
      "Tour agribusiness operations",
      "Prepare for the agriculture career fair",
      "Discuss commodity markets and farm policy",
    ],
    whatYouGain: [
      "A view of ag careers beyond production",
      "Contacts at cooperatives, lenders, and agribusiness firms",
      "Practical market knowledge",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "nama",
    name: "National Agri-Marketing Association",
    mark: "NAMA",
    slug: "national-agri-marketing-association",
    college: "College of Agriculture and Life Sciences",
    tagline:
      "Build a full agricultural marketing plan and take it to national competition.",
    summary:
      "The student chapter competes nationally by developing a complete marketing plan for a new agricultural product, from research through presentation. It is one of the more demanding and rewarding competition experiences in the college.",
    academicAreas: ["agriculture", "business"],
    openToAllMajors: true,
    majors: ["Agricultural Business", "Marketing", "Agricultural Communication"],
    categories: ["Agriculture", "Marketing", "Competition"],
    careerPaths: ["agriculture-food", "marketing", "media-comm"],
    goalsServed: ["career", "skills", "hands-on", "networking", "leadership"],
    experienceTypes: ["competition", "projects", "professional"],
    commitmentLevel: "involved",
    commitmentText: "About 4 to 6 hours a week during competition season",
    meetingFrequency: "Weekly team meetings plus project work",
    bestFor:
      "Students who want a full marketing project with a national audience.",
    whatYouDo: [
      "Research a market and develop a product concept",
      "Build a complete marketing plan with financials",
      "Present to industry judges at the national conference",
      "Meet agribusiness marketing professionals",
    ],
    whatYouGain: [
      "An end-to-end marketing project you led part of",
      "Presentation experience in front of industry judges",
      "A strong recruiting network in agricultural marketing",
    ],
    beginnerFriendly: false,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "pre-vet-club",
    name: "Pre-Veterinary Club",
    mark: "PV",
    slug: "pre-veterinary-club",
    college: "College of Agriculture and Life Sciences",
    tagline:
      "Get ready for veterinary school application with people doing the same thing.",
    summary:
      "Supports students preparing for veterinary school through speakers, hands-on wet labs, and guidance on the application process. Iowa State's veterinary college gives the club unusually good access to practicing veterinarians.",
    academicAreas: ["agriculture", "liberal-arts"],
    openToAllMajors: true,
    majors: ["Animal Science", "Biology", "Pre-Veterinary Medicine"],
    categories: ["Health", "Academic", "Community"],
    careerPaths: ["healthcare", "agriculture-food"],
    goalsServed: ["career", "skills", "hands-on", "community", "networking"],
    experienceTypes: ["academic", "professional", "community", "service"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 hours a week",
    meetingFrequency: "Regular meetings plus lab sessions",
    bestFor: "Students applying to veterinary school in the next few years.",
    whatYouDo: [
      "Attend wet labs and hands-on skill sessions",
      "Hear from veterinarians in small animal, large animal, and research paths",
      "Get guidance on veterinary school applications and experience hours",
      "Volunteer at animal-related events",
    ],
    whatYouGain: [
      "Hands-on hours that strengthen an application",
      "A realistic view of different veterinary career tracks",
      "Peers going through the same application cycle",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "prssa",
    name: "Public Relations Student Society of America",
    mark: "PRSSA",
    slug: "public-relations-student-society-of-america",
    college: "College of Liberal Arts and Sciences",
    tagline:
      "Communication strategy, client work, and a direct line into agencies.",
    summary:
      "The pre-professional organization for public relations and strategic communication students. Members take on client-facing communication work, build portfolios, and connect with agency professionals.",
    academicAreas: ["liberal-arts", "business"],
    openToAllMajors: true,
    majors: ["Public Relations", "Journalism", "Advertising", "Marketing"],
    categories: ["Communication", "Professional"],
    careerPaths: ["media-comm", "marketing"],
    goalsServed: ["career", "networking", "skills", "hands-on"],
    experienceTypes: ["professional", "projects"],
    commitmentLevel: "moderate",
    commitmentText: "About 2 to 3 hours a week",
    meetingFrequency: "Weekly meetings plus project work",
    bestFor:
      "Communication students who want agency experience before graduating.",
    whatYouDo: [
      "Work on communication projects for real clients",
      "Build a portfolio of writing and campaign work",
      "Hear from PR professionals and agency leaders",
      "Attend regional and national PRSSA conferences",
    ],
    whatYouGain: [
      "Portfolio pieces agencies actually ask to see",
      "Client communication experience",
      "A national network with an internship pipeline",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
  {
    id: "mock-trial",
    name: "Mock Trial",
    mark: "MT",
    slug: "mock-trial",
    college: "College of Liberal Arts and Sciences",
    tagline:
      "Argue a case in front of real judges against other university teams.",
    summary:
      "Teams prepare both sides of a case and compete at intercollegiate tournaments, taking the roles of attorneys and witnesses. It is the strongest public speaking and argument training available on campus, and not only for pre-law students.",
    academicAreas: ["liberal-arts", "business"],
    openToAllMajors: true,
    majors: ["Political Science", "Criminal Justice", "English", "Philosophy"],
    categories: ["Pre-Law", "Competition", "Academic"],
    careerPaths: ["media-comm", "consulting"],
    goalsServed: ["skills", "career", "community", "leadership"],
    experienceTypes: ["competition", "academic", "community"],
    commitmentLevel: "involved",
    commitmentText: "About 5 hours a week during competition season",
    meetingFrequency: "Weekly practices plus weekend tournaments",
    bestFor:
      "Students who want serious public speaking practice, pre-law or not.",
    whatYouDo: [
      "Learn a case file and prepare both prosecution and defense",
      "Perform as an attorney or a witness at tournaments",
      "Take and defend objections in real time",
      "Travel to intercollegiate competitions",
    ],
    whatYouGain: [
      "Public speaking ability that transfers to every career",
      "Comfort thinking on your feet under pressure",
      "A strong signal for law school applications",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: true,
  },
  {
    id: "pre-medical-club",
    name: "Pre-Medical Club",
    mark: "PM",
    slug: "pre-medical-club",
    college: "College of Liberal Arts and Sciences",
    tagline:
      "Navigate the medical school path with people a few steps ahead of you.",
    summary:
      "Support and guidance for students preparing for medical and health professional schools. Programming covers MCAT preparation, application timelines, physician panels, and finding clinical and volunteer experience.",
    academicAreas: ["liberal-arts", "human-sciences", "agriculture"],
    openToAllMajors: true,
    majors: ["Biology", "Biochemistry", "Kinesiology", "Genetics"],
    categories: ["Health", "Academic", "Community"],
    careerPaths: ["healthcare"],
    goalsServed: ["career", "community", "networking", "skills"],
    experienceTypes: ["academic", "professional", "service", "community"],
    commitmentLevel: "casual",
    commitmentText: "About 1 to 2 hours a week",
    meetingFrequency: "Meetings every other week",
    bestFor: "Students on a pre-health track who want structure and guidance.",
    whatYouDo: [
      "Hear from physicians and current medical students",
      "Work through MCAT and application planning",
      "Find clinical, shadowing, and volunteer opportunities",
      "Compare paths across medicine, PA, and other health professions",
    ],
    whatYouGain: [
      "A realistic timeline for the application process",
      "Leads on the experience hours schools expect",
      "A peer group that understands the workload",
    ],
    beginnerFriendly: true,
    freshmenWelcome: true,
    applicationRequired: false,
  },
];

export const clubBySlug = new Map(clubs.map((club) => [club.slug, club]));

export function getClub(slug: string): Club | undefined {
  return clubBySlug.get(slug);
}
